### ISSUE TITLE
Wrong MAX6675 multiplier

### ISSUE THREAD

**Issue by Seviged** [QIDITECH/klipper#4]
Greetings.

More than a year ago, @whb0514 posted a commit (08329f0) with changes to the MAX6675 multiplier.

However, the MAX6675 datasheet specifies a 12-bit resolution with 0.25°C per bit.

For example, if the ADC measures 1030, the temperature should be 1030 * 0.25 = 257.5°C.

But after that commit, the calculation would be 1030 * (0.25 * 0.95) = 244.625°C, which is more than a 10-degree difference.

Are you using a version of the MAX6675 with an unknown resolution of 0.2375°C? Or is this an attempt to compensate for a mechanical error?

**Comment by QIDITECH** [comment]
Yes, this change is to compensate for errors in the mechanical design and bring the measured temperature closer to the actual temperature.
