### ISSUE TITLE
adding filament change script

### ISSUE THREAD

**Issue by hosterweb1** [QIDITECH/klipper#7]
Hello. Please help me organize the process of changing the filament. As was done on my previous printer:
When it comes to changing the rod in gcode, the printer pauses and starts the filament change cycle. Unloads the old one, and gives a signal waiting for the new one to be loaded. After that, I manually remove the spool and put in a new one, load the filament into the extruder and press the button on the screen, and printing continues.
Plus 4 has commands m603 and m604, maybe I can implement it somehow with them?

**Comment by QIDITECH** [comment]
You can edit both Gcodes in gcode_macro.cfg
![微信截图_20241028084920](https://github.com/user-attachments/assets/ad52232a-2d67-4fef-92e6-611ef57a23e5)

**Comment by hosterweb1** [comment]
Whhat i should edit there? Can you help?

пн, 28 окт. 2024 г., 05:50 QIDI TECH ***@***.***>:

**Comment by QIDITECH** [comment]
You can directly edit M603 or M604 according to your needs
![image](https://github.com/user-attachments/assets/c066323b-34af-4c55-92c1-00e8b08cd806)

**Comment by hosterweb1** [comment]
Is there any way to call the menu on the printer screen from gcode? So that it would write something like "insert the rod and press ok" and launch m604?

**Comment by QIDITECH** [comment]
Sorry, this is not possible
