### ISSUE TITLE
Klipper/Mainsail updates for x-Smart 3

### ISSUE THREAD

**Issue by theclue** [QIDITECH/klipper#8]
I was wondering if an upgrade for klipper and mainsail is planned for the (not so old) x-Smart 3.

Apparently, they are so old the don't even support Spoolman Manager, which I actually use to manage my entire printer fleet but QIDI (and ofc this makes everything out of sync).

I know there are some procedures to total convert the printer with a standard klipper install, but it's way too invasive in my opionion if amn upgrade is already planned. And it would also break the warranty, I guess.

any feedback on that?

tnx allot!

**Comment by QIDITECH** [comment]
I'm sorry, we don't have that plan at the moment.
You can try updating yourself, but we can't guarantee anything will go wrong. As long as the hardware is not damaged, we can help you return the default version, please contact after-sales service.
